---
# handlers file for role-nagios

- name: restart nrpe
  service:
    name: "nrpe"
    state: restarted

- name: restart rsyslog
  service:
    name: "rsyslog"
    state: restarted

- name: plugin file permissions
  file:
    dest: "{{ nrpe_client_plugin_path }}"
    owner: nagios
    group: nagios
    mode: 0774
    recurse: yes
  listen: plugin permissions

- name: plugin dir permissions
  file:
    dest: "{{ nrpe_client_plugin_path }}"
    owner: nagios
    group: nagios
    mode: 0775
  listen: plugin permissions
